Uncommenting previous nights changes:tests and deleting ec2 included

diff --git a/.github/workflows/workflow_2.yml b/.github/workflows/workflow_2.yml
--- a/.github/workflows/workflow_2.yml
+++ b/.github/workflows/workflow_2.yml
@@ -4,7 +4,8 @@ on:
   workflow_run:
     workflows: ["Nightly Build"]
     types:
-      - success
+      - completed
+    if: ${{ github.event.workflow_run.conclusion == 'success' }}
   workflow_dispatch:
 
 env:
@@ -38,8 +39,7 @@ jobs:
            --image-id ami-05b10e08d247fb927 --count 1 \
            --instance-type t2.micro --key-name MyEC2KeyPair \
            --tag-specifications 'ResourceType=instance,Tags=[{Key=Name,Value=temp_EC2}]'
-        env:
-          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
+
       - name: Fetch IP of EC2
         run: |
           echo "Instance successfully launched"
@@ -47,6 +47,7 @@ jobs:
           export IP=$(aws ec2 describe-instances --filters "Name=tag:Name,Values=temp_EC2" --query 'Reservations[*].Instances[*].PublicIpAddress' --output text)
           echo $IP
           echo "IP=$IP" >> $GITHUB_ENV
+
       - name: Copying test, init.sql, docker-compose files from source repo to EC2
         run: |
           echo $IP
@@ -63,11 +64,11 @@ jobs:
       - name: Copy sh files
         run: |
           echo $IP
-          scp -i ~/.ssh/MyEC2KeyPair.pem -o StrictHostKeyChecking=no ./docker_build.sh ec2-user@$IP:~/
-          scp -i ~/.ssh/MyEC2KeyPair.pem -o StrictHostKeyChecking=no ./docker_setup.sh ec2-user@$IP:~/
-          scp -i ~/.ssh/MyEC2KeyPair.pem -o StrictHostKeyChecking=no ./ecr_steps.sh ec2-user@$IP:~/
+          scp -i ~/.ssh/MyEC2KeyPair.pem -o StrictHostKeyChecking=no ./dev/image_push.sh ec2-user@$IP:~/
+          scp -i ~/.ssh/MyEC2KeyPair.pem -o StrictHostKeyChecking=no ./dev/docker_setup.sh ec2-user@$IP:~/
+          scp -i ~/.ssh/MyEC2KeyPair.pem -o StrictHostKeyChecking=no ./dev/ecr_steps.sh ec2-user@$IP:~/
           
-      - name: Boot the containers
+      - name: Setup Docker and pull and run containers.
         run: |
           ssh -o StrictHostKeyChecking=no -i ~/.ssh/MyEC2KeyPair.pem ec2-user@"$IP" << 'EOF'
             export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
@@ -96,25 +97,34 @@ jobs:
             export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
             export AWS_SESSION_TOKEN=${{ secrets.AWS_SESSION_TOKEN }}
             export AWS_DEFAULT_REGION=${{ secrets.AWS_REGION }}
-            export FRONTEND_TIMESTAMP=$(docker images --format "{{.Repository}}:{{.Tag}}" | grep -E '^.*:frontend_' | awk -F: '{print $2}' | sort -V | head -n 1)
-            export BACKEND_TIMESTAMP=$(docker images --format "{{.Repository}}:{{.Tag}}" | grep -E '^.*:backend_' | awk -F: '{print $2}' | sort -V | head -n 1)
+            
             chmod +x test_2.sh
-            docker tag 343830488876.dkr.ecr.us-east-1.amazonaws.com/midterm/ecr_1:$BACKEND_TIMESTAMP 343830488876.dkr.ecr.us-east-1.amazonaws.com/midterm/ecr_2:$BACKEND_TIMESTAMP
-            docker tag 343830488876.dkr.ecr.us-east-1.amazonaws.com/midterm/ecr_1:$FRONTEND_TIMESTAMP 343830488876.dkr.ecr.us-east-1.amazonaws.com/midterm/ecr_2:$FRONTEND_TIMESTAMP
-            docker push 343830488876.dkr.ecr.us-east-1.amazonaws.com/midterm/ecr_2:$BACKEND_TIMESTAMP
-            docker push 343830488876.dkr.ecr.us-east-1.amazonaws.com/midterm/ecr_2:$FRONTEND_TIMESTAMP
+            ./test_2.sh
+            
+            if [ $? -ne 0 ]; then
+              echo "Tests failed"
+              aws ecr batch-delete-image \
+                --repository-name midterm/ecr_1 \
+                --image-ids imageTag=$BACKEND_TIMESTAMP
+
+              aws ecr batch-delete-image \
+                --repository-name midterm/ecr_1 \
+                --image-ids imageTag=$FRONTEND_TIMESTAMP
+            else
+              chmod +x image_push.sh
+              ./image_push.sh
+            fi
             exit 
           EOF
 
-      #- name: Deleting EC2 instance
-      #  if: failure()
-      #  run: |
-      #    export instance_id=$(aws ec2 describe-instances --filters \
-      #      "Name=instance-state-name,Values=running" \
-      #      "Name=tag:Name,Values=temp_EC2" --query 'Reservations[*].Instances[*].InstanceId' --output text)
-      #    echo "instance_id=$instance_id"
-      #    aws ec2 terminate-instances --instance-ids $instance_id
-      #    echo "Instance shutting down"
+      - name: Deleting EC2 instance
+        run: |
+          export instance_id=$(aws ec2 describe-instances --filters \
+            "Name=instance-state-name,Values=running" \
+            "Name=tag:Name,Values=temp_EC2" --query 'Reservations[*].Instances[*].InstanceId' --output text)
+          echo "instance_id=$instance_id"
+          aws ec2 terminate-instances --instance-ids $instance_id
+          echo "Instance shutting down"
           
           
           
